"""Models v3.0

Revision ID: 13f366b556ae
Revises: b9eebe40d244
Create Date: 2025-04-03 15:30:15.539998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f366b556ae'
down_revision = 'b9eebe40d244'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column('id_fita',
               existing_type=sa.UUID(),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column('id_fita',
               existing_type=sa.String(length=40),
               type_=sa.UUID(),
               existing_nullable=False)

    # ### end Alembic commands ###
