"""Models v1.0

Revision ID: 2005a43da63d
Revises: 
Create Date: 2025-03-25 20:59:48.615679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2005a43da63d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('instrucaoRobo')
    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('montagem', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=1),
               existing_nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('montagem', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=1),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('instrucaoRobo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_remedio', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instrucao', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_remedio'], ['lote.id'], name='instrucaoRobo_id_remedio_fkey'),
    sa.PrimaryKeyConstraint('id', name='instrucaoRobo_pkey')
    )
    # ### end Alembic commands ###
