"""Models-v3

Revision ID: 2e6828bec5f3
Revises: ac19e7116377
Create Date: 2025-03-24 23:19:54.687353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e6828bec5f3'
down_revision = 'ac19e7116377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrucaoRobo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_remedio', sa.Integer(), nullable=False),
    sa.Column('instrucao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_remedio'], ['lote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Integer(),
            postgresql_using="quantidade::integer")

    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column(
            'quantidade',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Integer(),
            postgresql_using="quantidade::integer"
        )

    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.alter_column(
            'quantidade',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Integer(),
            postgresql_using="quantidade::integer"
        )

    with op.batch_alter_table('montagem', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=1),
            type_=sa.Integer(),
            postgresql_using="status::integer"
        )



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('montagem', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=1),
               existing_nullable=False)

    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.drop_table('instrucaoRobo')
    # ### end Alembic commands ###
