"""vamooooo

Revision ID: 4843eb45536c
Revises: 3066a606ed5c
Create Date: 2025-04-08 17:22:52.732524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4843eb45536c'
down_revision = '3066a606ed5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrucaoRobo', schema=None) as batch_op:
        batch_op.alter_column('instrucao',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrucaoRobo', schema=None) as batch_op:
        batch_op.alter_column('instrucao',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
