"""Criando tabelas iniciais

Revision ID: 5ed4892f165b
Revises: 
Create Date: 2025-03-06 22:07:52.893782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed4892f165b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigo_bipado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barra', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codigo_bipado')
    # ### end Alembic commands ###
