"""InitialMigration

Revision ID: 8e4a7231fb87
Revises: 
Create Date: 2025-04-07 14:44:37.431838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4a7231fb87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('remedio', sa.String(length=100), nullable=False),
    sa.Column('compostoAtivo', sa.String(length=10), nullable=False),
    sa.Column('dose', sa.String(length=10), nullable=False),
    sa.Column('validade', sa.String(length=10), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('HC', sa.String(length=20), nullable=False),
    sa.Column('Leito', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.Text(), nullable=False),
    sa.Column('CPF', sa.String(length=11), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devolucao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_remedio', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_remedio'], ['lote.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instrucaoRobo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_remedio', sa.Integer(), nullable=False),
    sa.Column('instrucao', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_remedio'], ['lote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_remedio', sa.Integer(), nullable=False),
    sa.Column('id_fita', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['id_remedio'], ['lote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('montagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lista'], ['lista.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_lista')
    )
    op.create_table('erroMontagem',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_montagem', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_montagem'], ['montagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_montagem', sa.Integer(), nullable=False),
    sa.Column('id_remedio', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_montagem'], ['montagem.id'], ),
    sa.ForeignKeyConstraint(['id_remedio'], ['lote.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('erroMontagem')
    op.drop_table('montagem')
    op.drop_table('lista')
    op.drop_table('instrucaoRobo')
    op.drop_table('devolucao')
    op.drop_table('usuario')
    op.drop_table('paciente')
    op.drop_table('lote')
    # ### end Alembic commands ###
