"""Models v2.0

Revision ID: a2db8f63bfa5
Revises: 2005a43da63d
Create Date: 2025-03-26 11:59:48.670087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2db8f63bfa5'
down_revision = '2005a43da63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrucaoRobo',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('id_remedio', sa.Integer(), nullable=False),
        sa.Column('instrucao', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['id_remedio'], ['lote.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.alter_column(
            'quantidade',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using="quantidade::integer"
        )

    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column(
            'quantidade',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using="quantidade::integer"
        )

    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.alter_column(
            'quantidade',
            existing_type=sa.VARCHAR(length=10),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using="quantidade::integer"
        )

    with op.batch_alter_table('montagem', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=1),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using="status::integer"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('montagem', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=1),
            existing_nullable=False,
            postgresql_using="status::varchar"
        )

    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.alter_column(
            'quantidade',
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
            postgresql_using="quantidade::varchar"
        )

    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column(
            'quantidade',
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
            postgresql_using="quantidade::varchar"
        )

    with op.batch_alter_table('devolucao', schema=None) as batch_op:
        batch_op.alter_column(
            'quantidade',
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=10),
            existing_nullable=False,
            postgresql_using="quantidade::varchar"
        )
    op.drop_table('instrucaoRobo')
    # ### end Alembic commands ###
