"""Models-v2

Revision ID: ac19e7116377
Revises: 9611e62fe4da
Create Date: 2025-03-22 14:09:04.977642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac19e7116377'
down_revision = '9611e62fe4da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compostoAtivo', sa.String(length=10), nullable=False))
        batch_op.drop_column('compostaAtivo')

    with op.batch_alter_table('montagem', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('montagem', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('lote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compostaAtivo', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('compostoAtivo')

    # ### end Alembic commands ###
