"""Models v3.0

Revision ID: b9eebe40d244
Revises: e659a98d5481
Create Date: 2025-04-03 11:23:49.735937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9eebe40d244'
down_revision = 'e659a98d5481'
branch_labels = None
depends_on = None


def upgrade():
    # Conversão explícita de id_fita de INTEGER para UUID
    op.execute("""
        ALTER TABLE lista
        ALTER COLUMN id_fita
        TYPE UUID
        USING id_fita::text::uuid;
    """)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.alter_column('id_fita',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
