"""Models v3.0

Revision ID: e659a98d5481
Revises: a2db8f63bfa5
Create Date: 2025-04-02 17:18:53.157282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e659a98d5481'
down_revision = 'a2db8f63bfa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_fita', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lista', schema=None) as batch_op:
        batch_op.drop_column('id_fita')

    # ### end Alembic commands ###
